LOCAL_PATH := $(call my-dir)

$(call add-radio-file,abl.img)
$(call add-radio-file,aop.img)
$(call add-radio-file,bluetooth.img)
$(call add-radio-file,cpucp.img)
$(call add-radio-file,devcfg.img)
$(call add-radio-file,dsp.img)
$(call add-radio-file,engineering_cdt.img)
$(call add-radio-file,featenabler.img)
$(call add-radio-file,hyp.img)
$(call add-radio-file,imagefv.img)
$(call add-radio-file,keymaster.img)
$(call add-radio-file,modem.img)
$(call add-radio-file,multiimgoem.img)
$(call add-radio-file,oplus_sec.img)
$(call add-radio-file,oplusstanvbk.img)
$(call add-radio-file,qupfw.img)
$(call add-radio-file,qweslicstore.img)
$(call add-radio-file,shrm.img)
$(call add-radio-file,splash.img)
$(call add-radio-file,tz.img)
$(call add-radio-file,uefisecapp.img)
$(call add-radio-file,xbl.img)
$(call add-radio-file,xbl_config.img)
