LOCAL_PATH := $(call my-dir)

$(call add-radio-file,abl.elf)
$(call add-radio-file,adspso.bin)
$(call add-radio-file,BTFM.bin)
$(call add-radio-file,cmnlib.mbn)
$(call add-radio-file,cmnlib64.mbn)
$(call add-radio-file,devcfg.mbn)
$(call add-radio-file,hyp.mbn)
$(call add-radio-file,keymaster.mbn)
$(call add-radio-file,logo.bin)
$(call add-radio-file,NON-HLOS.bin)
$(call add-radio-file,pmic.elf)
$(call add-radio-file,rpm.mbn)
$(call add-radio-file,static_nvbk.bin)
$(call add-radio-file,tz.mbn)
$(call add-radio-file,xbl.elf)
