LOCAL_PATH := $(call my-dir)

$(call add-radio-file,abl.img)
$(call add-radio-file,bl1.img)
$(call add-radio-file,bl2.img)
$(call add-radio-file,bl31.img)
$(call add-radio-file,gsa.img)
$(call add-radio-file,ldfw.img)
$(call add-radio-file,modem.img)
$(call add-radio-file,pbl.img)
$(call add-radio-file,tzsw.img)
