LOCAL_PATH := $(call my-dir)

$(call add-radio-file,abl.img)
$(call add-radio-file,apdp.img)
$(call add-radio-file,bootloader.img)
$(call add-radio-file,cmnlib.img)
$(call add-radio-file,cmnlib64.img)
$(call add-radio-file,devcfg.img)
$(call add-radio-file,dtbo.img)
$(call add-radio-file,hyp.img)
$(call add-radio-file,keymaster.img)
$(call add-radio-file,modem.img)
$(call add-radio-file,msadp.img)
$(call add-radio-file,pmic.img)
$(call add-radio-file,radio.img)
$(call add-radio-file,rpm.img)
$(call add-radio-file,tz.img)
$(call add-radio-file,xbl.img)
