LOCAL_PATH := $(call my-dir)

$(call add-radio-file,abl.img)
$(call add-radio-file,aop.img)
$(call add-radio-file,bluetooth.img)
$(call add-radio-file,cmnlib.img)
$(call add-radio-file,cmnlib64.img)
$(call add-radio-file,devcfg.img)
$(call add-radio-file,dsp.img)
$(call add-radio-file,fw_4j1ed.img)
$(call add-radio-file,fw_4u1ea.img)
$(call add-radio-file,hyp.img)
$(call add-radio-file,keymaster.img)
$(call add-radio-file,LOGO.img)
$(call add-radio-file,modem.img)
$(call add-radio-file,oem_stanvbk.img)
$(call add-radio-file,qupfw.img)
$(call add-radio-file,storsec.img)
$(call add-radio-file,tz.img)
$(call add-radio-file,xbl.img)
$(call add-radio-file,xbl_config.img)
